### PR TITLE
fix: update it to use GITHUB_OUTPUT

### LINKED ISSUE #22: GitHub Actions: Deprecating save-state and set-output commands
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### PR DESCRIPTION
**Pull request by tryvin**
GitHub has updated its requirements to now have actions use `$GITHUB_OUTPUT` instead of `::set-output`

Closes #22

### CODE REVIEW

File: slugify.sh [hunk 1]
```diff
@@ -57,11 +57,11 @@ SLUG_CS_VALUE=$(slug "$CS_VALUE")
...
-echo "::set-output name=value::${CS_VALUE}"
-echo "::set-output name=slug::${SLUG_VALUE}"
-echo "::set-output name=slug-cs::${SLUG_CS_VALUE}"
-echo "::set-output name=slug-url::${SLUG_URL_VALUE}"
-echo "::set-output name=slug-url-cs::${SLUG_URL_CS_VALUE}"
+echo "value=${CS_VALUE}" >> $GITHUB_OUTPUT
+echo "slug=${SLUG_VALUE}" >> $GITHUB_OUTPUT
+echo "slug-cs=${SLUG_CS_VALUE}" >> $GITHUB_OUTPUT
+echo "slug-url=${SLUG_URL_VALUE}" >> $GITHUB_OUTPUT
+echo "slug-url-cs=${SLUG_URL_CS_VALUE}" >> $GITHUB_OUTPUT
```
Comment (rlespinasse) [inline slugify.sh]: Use the following syntax instead

```shell
{
   echo "key1=${value1}"
   echo "key2=${value2}"
} >>"$GITHUB_OUTPUT"

Comment (tryvin) [reply slugify.sh]: @rlespinasse Updated!
